use bytey::{ByteBufferRead, ByteBufferWrite};
use serde::{Deserialize, Serialize};

#[derive(
    Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ByteBufferRead, ByteBufferWrite,
)]
#[repr(u32)]
pub enum ServerPackets {
    OnlineCheck,
    AlertMsg,
    FltAlert,
    HandShake,
    LoginOk,
    MapItems,
    MyIndex,
    Move,
    MoveOk,
    Warp,
    Dir,
    Vitals,
    Attack,
    Death,
    PlayerData,
    PlayerSpawn,
    PlayerInv,
    PlayerInvSlot,
    PlayerStorage,
    PlayerStorageSlot,
    PlayerEquipment,
    PlayerLevel,
    PlayerMoney,
    PlayerPk,
    NpcData,
    ChatMsg,
    EntityUnload,
    OpenStorage,
    OpenShop,
    ClearIsUsingType,
    UpdateTradeItem,
    UpdateTradeMoney,
    InitTrade,
    TradeStatus,
    TradeRequest,
    PlayItemSfx,
    Damage,
    Ping,
}

#[derive(
    Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ByteBufferRead, ByteBufferWrite, Hash,
)]
pub enum ClientPacket {
    OnlineCheck,
    Register,
    Login,
    HandShake,
    Move,
    Dir,
    Attack,
    UseItem,
    Unequip,
    SwitchInvSlot,
    PickUp,
    DropItem,
    DeleteItem,
    SwitchStorageSlot,
    DeleteStorageItem,
    DepositItem,
    WithdrawItem,
    Message,
    Command,
    SetTarget,
    CloseStorage,
    CloseShop,
    CloseTrade,
    BuyItem,
    SellItem,
    AddTradeItem,
    RemoveTradeItem,
    UpdateTradeMoney,
    SubmitTrade,
    AcceptTrade,
    DeclineTrade,
    Ping,
    Size,
}
